### ISSUE TITLE
Feature request: Option to filter SNPs with low sequence coverage

### ISSUE THREAD

**Issue by jdblischak** [statgen/verifyBamID#3]
Would it be possible to add an option to filter SNPs with low sequence coverage? The [documentation](http://genome.sph.umich.edu/wiki/VerifyBamID) warns that SNPs with low coverage will negatively impact the analysis:

>  IMPORTANT : For targeted sequencing data, it is important to subselect the markers to only include on-target markers in the genotype file. Off-target markers are not likely to have multiple non-duplicated reads at the marker position, and it may create artifacts in the analysis due to overlapping fragments.

I ask because I want to try to use verifyBamID with RNA-seq data, which I think should be analogous to low coverage targeted DNA sequencing*. Because which genes that are expressed at a high enough level to generate sufficient coverage can vary between conditions (e.g. across tissues), having to first filter SNPs for sufficient coverage before running verifyBamID would add considerable computational overhead to this QC check.

\* I am aware of a few differences. First, the presence of allele-specific expression could affect the inference for heterozygous sites in an individual. But I expect this to only affect a subset of sites, and I assume it will only add noise (and not bias). The only way it could cause a bias is if there was another individual in the study that was homozygous for the preferentially expressed allele in a different individual across many sites. Second, there is more unequal coverage across sites in RNA-seq due to differences in expression level, but again I think it would be unlikely that this would cause one individual to be identified as another. Please let me know if there are caveats that I have not considered.

Thanks!

**Comment by jdblischak** [comment]
The SNPs with low coverage did not impact my analysis enough to give me a wrong answer for any of my test samples. I used the set of SNPs that overlap annotated exons of human protein-coding genes. This was 528,289 SNPs, of which 311,848 passed the default allele frequency and call rate thresholds. Here's an example of one of the depth files, demonstrating how the majority of SNPs had zero coverage.

```
#RG     DEPTH   #SNPs   %SNPs   %CUMUL
ALL     20      2624    0.00841 0.00841
ALL     19      19      0.00006 0.00848
ALL     18      14      0.00004 0.00852
ALL     17      20      0.00006 0.00858
ALL     16      15      0.00005 0.00863
ALL     15      21      0.00007 0.00870
ALL     14      18      0.00006 0.00876
ALL     13      12      0.00004 0.00880
ALL     12      9       0.00003 0.00882
ALL     11      17      0.00005 0.00888
ALL     10      17      0.00005 0.00893
ALL     9       19      0.00006 0.00899
ALL     8       21      0.00007 0.00906
ALL     7       43      0.00014 0.00920
ALL     6       54      0.00017 0.00937
ALL     5       51      0.00016 0.00954
ALL     4       81      0.00026 0.00980
ALL     3       157     0.00050 0.01030
ALL     2       475     0.00152 0.01182
ALL     1       3304    0.01059 0.02242
ALL     0       304857  0.97758 1.00000
```

**Comment by jdblischak** [comment]
Just in case anyone else that is interested in using verifyBamID with RNA-seq data, I wanted to update this thread now that I've read the paper that describes the method ([Jun et al., 2012](http://www.ncbi.nlm.nih.gov/pubmed/23103226)). Even though the [documentation](http://genome.sph.umich.edu/wiki/VerifyBamID) for verifyBamID does not mention the possibility of using it with RNA-seq data, the publication does. From the Discussion:

> We also found that our sequence-based methods robustly detect
> contamination in RNA-seq data with or without external genotypes. In
> these data sets, focusing on exonic or on-target sites provided more
> accurate estimates of contamination levels than using all sites (data
> not shown).

**Comment by hyunminkang** [comment]
The cleanCall package at https://github.com/hyunminkang/cleanCall now support this feature. We plan to update verifyBamID similarly, but CRAM support is more important, and we will have to make some major update to make it compatible to htslib
