### ISSUE TITLE
v1.1.3 - nothing in bin for tgz

### ISSUE THREAD

**Issue by keiranmraine** [statgen/verifyBamID#5]
tgz binary attachment to the release has nothing in the bin directory

**Comment by mktrost** [comment]
Sorry for the confusion.  The tgz file in the release is the uncompiled source code.  I did not realize that github also provided it as a download.  The verifyBamIDLibStatGen.1.1.3.tgz file also includes the source code for libStatGen  (also uncompiled).

**Comment by jrandall** [comment]
There still appears to be no binary release provided for 1.1.3

**Comment by mktrost** [comment]
I added a binary built on ubuntu.   
https://github.com/statgen/verifyBamID/releases/download/v1.1.3/verifyBamID

Let me know if that works for you.  Another option would be to build from source.
